// Generated by Bison
#include "json.tab.h"

/*
A simple (a.k.a. incomplete) JSON validator.
Made as an example to show how to use flex and bison.
*/

int main() {
	// Just calls yyparse.
	// Obviously, you might want to do something more complex here.
	yyparse();
}
